name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Replace with the default branch of your repository if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

   - name: Build and Deploy React App
      run: npm run deploy
      env:
    DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

